platform :ios, ‘8.0’
use_frameworks!

def testing_pods
    pod 'ReactiveCocoa’, ‘2.1.8’
    pod 'OHHTTPStubs'
    pod ‘AFNetworking’
    pod 'SAMKeychain'
    pod ‘GoogleMaps’
pod 'MBProgressHUD'
end

target ‘Jitensha’ do
    	testing_pods
end
 
target ‘JitenshaTests’ do
	testing_pods
end

