platform :ios, ‘8.0’
use_frameworks!

def testing_pods
    pod 'ReactiveCocoa', '2.1.8'
    pod 'OHHTTPStubs'
end

target ‘ColorsStatistics’ do
    testing_pods
end
 
target ‘ColorsStatisticsTests’ do
	testing_pods
end

