# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sibedge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sibedge
  pod 'RxAlamofire'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 4.0'
  pod 'ImageSlideshow/Kingfisher'

  target 'sibedgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sibedgeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
